### ISSUE TITLE
eslint-nuxt plugin

### ISSUE THREAD

**Issue by manniL** [nuxt/rfcs#13]
On the long run we should think about an `eslint-nuxt` plugin that makes DX for Nuxt devs even better!

Some rule ideas:

* Warning/Error when using `this` in `asyncData/fetch`
* Warning/Error when using `window/document` in `created/beforeCreate`
* ...

**Main work**: @clarkdo 
**Repo**: https://github.com/nuxt/eslint-plugin-nuxt

**Comment by clarkdo** [comment]
- No invalid plugin `mode` in 'nuxt.config.js'

**Comment by cannap** [comment]
- when i18n package is used warn to use localPath function in <nuxt-link :to="localPath>
