### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by manniL** [nuxt/rfcs#18]
placeholder

related PRs: https://github.com/nuxt/nuxt.js/pull/4406

**Comment by kevinmarrec** [comment]
I commited a draft on my fork : https://github.com/kevinmarrec/nuxt.js/commit/b245de88bdaf8e7d2040d048024ca53a31da4fa0

I've issues with TSX but that's because I'm not using the babel preset but only the babel plugin, so the TSX support is missing I guess, will try something tonight :)

**Comment by kevinmarrec** [comment]
I think my way to setup a `typescript` Nuxt Config option is the best solution.

Cause with other solutions it will instantly break every project using a TypeScript Module (from npm or local one). Cause there will be both Babel and TsLoader doing things.

With the `typescript` option, TS users will be able to either have their custom TS module or enable built-in Nuxt support with `typecript: true`.

**Comment by hartmut-co-uk** [comment]
the interoperability / -> not breaking / allowing custom setup is a good point indeed!

**Comment by kevinmarrec** [comment]
Fixed TSX rolling back to `@babel/preset-typescript` instead of using only the `@babel/plugin-transform-typescript`
https://github.com/kevinmarrec/nuxt.js/commit/5273a5e195c22e32f3ddcf625fccd19ba4d89590

**Comment by kevinmarrec** [comment]
Nice glob post to read to https://iamturns.com/typescript-babel

We'll need to copy this link or explain the caveats of
https://babeljs.io/docs/en/next/babel-plugin-transform-typescript
in Nuxt documentation.

**Comment by pi0** [comment]
please please use discord or nuxt issues for general discussions instead of RFC 🙏  A normal RFC process should be in form of a detailed writedown about changes, more discussions and implemented by one or more PRs referencing to the issue.

**Comment by kevinmarrec** [comment]
@pi0 Sorry !

**Comment by manniL** [comment]
@pi0 I thought we could use it to clearly state how we want to implement the TS support :thinking:

**Comment by ksnyde** [comment]
@pi0 I'm a bit confused by your comment, just wanting clarification. In this thread we are discussing an RFC. You seemed to suggest Discord/NUXT issues as more appropriate? I do think think the RFC thread is too bare to be a starting point currently but wouldn't this conversation -- which has both momentum and high value (IMO) -- be better served working off of an RFC? That's certainly how we'd have done it in the Ember community (although the bare bones RFC would not have been allowed). I think whomever started the RFC ... @manniL is that you? ... should take a next step to formalize the RFC too but I'd strongly prefer if this didn't slow down the movement that this thread is already generating.

**Comment by ksnyde** [comment]
I'm new to NUXT so please take my comments only as exploratory, I expect I'll be bumping into walls a bit to start.
