### ISSUE TITLE
Fabula

### ISSUE THREAD

**Issue by galvez** [nuxt/rfcs#20]
The contents of this RFC moved [to the actual documentation][docs] for the [alpha version][alpha]. In a nutshell, **Fabula** is a Vue/Nuxt-inspired tool for running tasks on local and remote hosts.

[docs]: https://nuxt.github.io/fabula
[alpha]: https://github.com/nuxt/fabula

**Note**: alpha version source code not publicly available yet.

**Comment by Atinux** [comment]
Thank you @galvez for this well formatted RFC :)

To give some context, I have no idea about Fabric or other kind of experiences about Shell script, so my opinion may not be really pertinent on some details.

First of all, I do believe a Nuxt shell script preprocessor could be a good idea, I am not sure if this has to be part of the core since most of the users may never use it (spa mode, static generation, or people using solutions like Now, Heroku, etc.) if this is specific to `ssh`/`servers` scripts.

I would like to listen from @pi0 and @aldarund on this since they are more experienced than I on dev ops.

**Comment by galvez** [comment]
@Atinux just to be clear, I don't mean this to be part of Nuxt server/rendering core -- I'm calling it `@nuxt/operations` simply due to the easy aesthetics of the name (and to indicate its _official_ status).

**Comment by pi0** [comment]
Nice ideas. Following fabric conventions, adding Nuxt.js like sexy usage and more important replacing python with JS. But honestly, I suggest it to be a stand-alone tool for operations. 
My main reason to focus on making a standalone utility for SSH operations is a separation of concerns.

- Lamda: This could be focused in an standalone module for packaging only - Independent of the way of deployment (AWS/Now2/etc)
- DB Migrations: I'm sure there are already battle-tested libraries for backend frameworks
- Docker, Kubernetes: We really need them. This is again out of the scope of this utility IMO

For Nuxt.js integration, we can create a community module package that ties nuxt config / nuxt commands to this module for operations We can also keep this repo in the official nuxt org. Like consola to indicate is's official status.

**Comment by galvez** [comment]
@pi0 @Atinux went ahead and renamed the repo to `fabula` (and reserved the npm name as well). I like the idea of having a separate Nuxt community module (perhaps `@nuxtjs/ops` simply) that uses the `fabula` shell language. I'll proceed with this unless anyone strongly feels there's a better name :)

**Comment by Atinux** [comment]
I do like fabula ❤️

Sent via Superhuman iOS ( https://sprh.mn/?vip=atinux@gmail.com )

**Comment by galvez** [comment]
@Atinux @pi0 @aldarund @manniL @clarkdo so Fabula reached **0.1.6** (alpha) today. I ask your review/comments on the following implementations:

- https://nuxt.github.io/fabula/logging.html
  - https://github.com/nuxt/fabula/blob/master/src/logging.js
  - https://github.com/nuxt/fabula/blob/master/src/command.js
  - https://github.com/nuxt/fabula/blob/master/test/unit/logging.test.js
  - https://github.com/nuxt/fabula/blob/master/test/server.js (SSH test server)

https://nuxt.github.io/fabula/failure.html#handlers
  - https://github.com/nuxt/fabula/blob/master/src/command.js
  - https://github.com/nuxt/fabula/blob/master/src/local.js
  - https://github.com/nuxt/fabula/blob/master/src/commands/exec.js

Test suite now covers connection, success/error handling and logging from local and remote hosts. There are few more tests to be done before the public release, but I'm exceedingly satisfied with we've got so far :)
