### ISSUE TITLE
@nuxt/sse: Server-sent Events for Nuxt

### ISSUE THREAD

**Issue by Atinux** [nuxt/rfcs#36]
## Introduction

Introducing a [Server-sent events](https://en.wikipedia.org/wiki/Server-sent_events#targetText=Server%2DSent%20Events%20(SSE),of%20HTML5%20by%20the%20W3C.) module for Nuxt to let [serverMiddleware](https://nuxtjs.org/api/configuration-servermiddleware#the-servermiddleware-property) and [functions](https://github.com/nuxt/rfcs/issues/35) to send events to the Nuxt app.

An instance will be available with `nuxt.$sse` to send events.

`nuxt.config.js`:
``` js
import fetch from 'node-fetch'

export default {
  hooks: {
   ready(nuxt) {
      setInterval(async () => {
         const tweets = await fetch(`https://api.example.com/tweets?from=${Date.now()-2000}`).then(res => res.json())
         tweets.forEach(tweet => nuxt.$sse.broadcast('tweet', tweet))
      }, 2000)
    }
  }
}
```

On the app side, it will expose a `$sse` instance with `.on('eventName', fn)`.

`pages/tweets.vue`:
```js
<template>
  <ul>
     <li v-for="tweet of tweets">...</li>
  </ul>
</template>

<script>
export default {
  async asyncData() {
     const tweets = await fetch('/api/tweets').then(res => res.json())

     return { tweets }
  }},
  mounted() {
    this.$sse.on('tweet', (tweet) => this.tweets.unshift(tweet))
  }
}
</script>
```

## How does it work?

`@nuxt/sse` will:
1. Create a serverMiddleware on `/_nuxt/sse` (see more [here](https://github.com/nuxt/loading-screen/blob/master/lib/sse.js))
2. Inject `nuxt.$sse`
3. Inject `$sse` in the Nuxt app **on client-side** with `this.addPlugin` + auto connect + customisable with a custom endpoint

With this system, modules author could inject this module to add some realtime data to the Nuxt app easily 🚀 

PS: 0 breaking change 😇

**Comment by DreaMinder** [comment]
Woah, it looks awesome!
But one thing should be kept in mind: SSE is kind of abandoned technology: https://github.com/whatwg/html/issues/2177#issuecomment-332071504

Maybe someday it will be rewritten to Fetch API implementation (according to the link). For example to enable auth-headers support.

**Comment by Amaurgit** [comment]
So, no nuxt/sse ? :) I got a :  

`EventSource's response has a MIME type ("application/json") that is not "text/event-stream". Aborting the connection. `  

because of the webpack HMR I guess. Any update on this ? :)

**Comment by linqFR** [comment]
Hello @Atinux 

any doc anywhere about sse?

**Comment by lewebsimple** [comment]
Just wanted to link this issue with my current progress at using SSE in Nuxt3. Basically I'm stuck because unjs/h3 seems to close the connection no matter what I do.

See [this issue](https://github.com/unjs/h3/issues/85) and [reproduction repository](https://github.com/lewebsimple/nuxt3-sse-reproduction) for details.
