### ISSUE TITLE
Blueprints

### ISSUE THREAD

**Issue by pimlie** [nuxt/rfcs#37]
# Introduction

Nuxt blueprints will be a way of distributing a _micro-like-framework_ for Nuxt.js utilizing a Nuxt.js module. It follows (more or less) the same folder pattern as Nuxt.js and automatically registers any special components/scripts in the proper _Nuxt way_.

## History

Basic concept of this rfc is based on work done by @galvez for NuxtPress. Not sure where his ideas were based on.

## How does it work?

A blueprint will just be a _supercharged_ Nuxt.js module (at least for starters, i.e. _start small, grow big_). E.g. currently the Nuxt.js module container provides only _singular_ methods, meaning you can only register e.g. one plugin at the time (:bike:) . A blueprint module supports adding multiple plugins at the time (:bus:)

It will also provide a helper function to automatically discover template files within a folder to include. Those files can then be added all at once using another special resolver function.

If you dont like things to happen _automagically_, you could also just call the corresponding functions yourself

## Isnt that module inception?

Yes, if you create a blueprint you create a module based on the blueprint module which uses the module container. A _dream level 3_ module if you like :upside_down_face: :open_mouth: :upside_down_face: 

## Why not just add these features to the moduleContainer?

Cause that could potentially break existing modules (although unlikely). Also nice to have separation of concerns, a blueprint will be so much more then just a module that it makes sense to split this.

## Ok, but what about #30?

Same but different. Probaby this rfc evolved from that one, but the approach is a bit different. This rfc is module-centric and mainly utilizes only existing Nuxt features<sup>1</sup>

<small><sup>1</sup> Existing as in available in nuxt-edge because some missing features have just been added to Nuxt.js</small>

## When will it be ready?

The basics have already been developed for [Nuxt/Press](https://github.com/nuxt/press/blob/fixes-v0.2/packages/utils/src/blueprint.js)

## Why this rfc when its already available?

The NuxtPress implementation is/might not be generic (enough). This rfc is to find out what is missing.

## I still dont get it?

To _show by example_, please explore the [`fixes-v0.2`](https://github.com/nuxt/press/tree/fixes-v0.2/packages) branch of NuxtPress and read the _blueprint_ & _common replaced with core_ sections of [this pr](https://github.com/nuxt/press/pull/60). Its a working example of what you can do with blueprints.

# Feature wishlist

_[x] = already implemented_

- [x] autodiscovery of templates
- [x] adding all files/templates at once
- [x] copy files instead of treating every file as a template
- [x] support for using multiple instances of a blueprint
- [x] support copying a template for every instance of a blueprint
- [x] prevent a blueprint from being instantiated more then once
- [x] add custom template options
- [x] add webpack aliases so you can use 'absolute' paths in your templates
- [ ] adding Nuxt.js vue-app overrides (app overrides)
- [ ] adding store modules
- [x] ejecting blueprint templates
- [x] proper testing
- [ ] remove nuxt-edge dependency

**Comment by pi0** [comment]
> Hmm, but then what about #10 ?
> That's a long term vision, this is short term.

I don't agree this with one. Blueprints are somehow successor of #30 but module utils is not a long term vision and we soon should start refactoring helpers/common use cases out of the main module-container. Maybe blueprints can at a point use these utils as well.

**Comment by pimlie** [comment]
First alpha release is available: https://github.com/nuxt/blueprints
