### ISSUE TITLE
Release Plan

### ISSUE THREAD

**Issue by pi0** [nuxt/rfcs#9]
# Update

We have decided on a release plan which will take effect with `v2.4`.
We try to abide to the plan as good as possible *but* it is thought as a rough schedule overview. There won't be an **exact** release date for most of the future versions.

# Initial content
Current release lines:

- **Edge:**
  - Usage is not documented 
  - No changelogs (we can have a much better one if Lerna used correctly)
  - Automated release after each commit to the `dev` branch
  - All tests should be passing on circleCI with an acceptable amount of coverage (80-90%)
  - Weekly downloads for `nuxt-edge`: `39,421`

- **Stable:**
  - Usage is documented 
  - Goodchangelogs
  - Manual release after a certain amount of changes to the develop
  - Weekly downloads for `nuxt`: `61,321` 

- **LTS:** 
  - Usage is not documented
  - Good changelogs
  - Manual release on demand
  - For each major version, we have a `1.x`/`2.x`/.. branch that contains the latest changes before the next major one
  - Critical security updates are not being applied
  - Usually, contain backported fixes and enhancements
  - Weekly downloads not clear!

Concerns:

- `master` branch is not actively updated nor has clear utility.
- No mechanism for handling PRs with `BREAKING CHANGES`. We simply convert `dev` purpose to `next` when the first PR with breaking change ships. This prevents faster iterations while easily accepting breaking changes. We need another branch like `next` which is kept in sync with `dev` (automation possible?) and also ship breaking changes there and merge into `dev` accoring to release schedules. Sub concern -> We need `edge@next` then 😆 
- **Important:** There is not any scheduled plan for Stable releases. Enterprise world needs estimate.
- **Important:** We don't officially have an LTS line. Having one is another step towards being more enterprise friendly. I know too many companies that are lazy are still using nuxt 1 that more than DX bugs, doesn't contain security updates for sub-packages! (The last part may be automated too)

**Comment by manniL** [comment]
The release plan will be published with v2.4

**Comment by manniL** [comment]
Final PR in https://github.com/nuxt/nuxt.js/pull/4853
